Description of executeGrabOneCallback
Home > Imaging > guis > gui_callbacks > executeGrabOneCallback.m
executeGrabOneCallback
PURPOSE
SYNOPSIS
function executeGrabOneCallback
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
setStatusString This function sets the status field in mainControls.
savingInfoIsOK updated by tp 10/25/01
timerCallPackageFunctions
timerSetActiveStatus
This function is called by:
siGUI_ImagingControls siGUI_ImagingControls Application M-file for siGUI_ImagingControls.fig
executeGrabOneStackCallback executeGrabOneCallback(h).m******
SpineSelect
stackAndBlast
SOURCE CODE
function executeGrabOneCallback
    global state gh
    state.internal.looping=0;
    val=get(gh.siGUI_ImagingControls.grabOneButton, 'String');
    persistent multipleAbortAttempts
    if (exist('multipleAbortAttempts', 'var')~=1)
        multipleAbortAttempts=0;
    end
    if strcmp(val, 'GRAB')
        if strcmp(get(gh.basicConfigurationGUI.figure1, 'Visible'), 'on') == 1
            beep;
            setStatusString('Close Configuration GUI');
            return
        end
        if ~savingInfoIsOK
            return
        end
        multipleAbortAttempts=0;
        timerSetActiveStatus('Imaging', 1);
        timerCallPackageFunctions('FirstSetup', 'Imaging');
        timerCallPackageFunctions('Setup', 'Imaging');
        timerCallPackageFunctions('Start', 'Imaging');
        state.cycle.loopingStatus=0;
        global grabInput
        start(grabInput);
        trigger(grabInput);
    elseif strcmp(val, 'ABORT')
        timerCallPackageFunctions('Abort', 'Imaging');
        multipleAbortAttempts=multipleAbortAttempts+1;
        if multipleAbortAttempts>1
            multipleAbortAttempts=multipleAbortAttempts+1;
            disp('Multiple abort attempts.  Will force abort.');
            timerCallPackageFunctions('ForcedAbort', 'Imaging');
        end
    else
        disp('executeGrabOneCallback: Grab One button is in unknown state');     % BSMOD - error checking
    end