Description of openini
Home > Imaging > io > file_io > initialization > openini.m
openini
PURPOSE
SYNOPSIS
function out=openini(fileName)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
initGUIs opens and interprets and initialization file
This function is called by:
initFluorAnalysis
initImaging
initTiler
initTimer
initTraceAnalysis
SOURCE CODE
function out=openini(fileName)
    out=1;
    [fid, message]=fopen(fileName);
    if fid<0
        disp(['openini: Error opening ' fileName ': ' message]);
        out=1;
        return
    end
    [fileName,permission, machineormat] = fopen(fid);
    fclose(fid);
    disp(['*** CURRENT INI FILE = ' fileName ' ***']);
    initGUIs(fileName);
    [path,name,ext] = fileparts(fileName);
    global state;
    state.iniName=name;
    state.iniPath=path;