Description of getGUIValue
Home > Imaging > guis > gui_handling > getGUIValue.m
getGUIValue
PURPOSE
returns the value in a GUI
SYNOPSIS
function out=getGUIValue(handle)
DESCRIPTION
 returns the value in a GUI
CROSS-REFERENCE INFORMATION
This function calls:
getUserDataField returns value of field in 'UserData' or [] if that field does not exist
hasUserDataField checks if a field exists within the 'UserData' of a particular handle
This function is called by:
updateGUIGlobal update the value of a Global value to match that contained in its GUI
updateGUILinks
SOURCE CODE
function out=getGUIValue(handle)
% returns the value in a GUI
    style=get(handle, 'Style');
    if strcmp(style, 'edit')
        out=get(handle, 'String');
        if hasUserDataField(handle, 'Numeric')
            if getUserDataField(handle, 'Numeric')
                out=str2num(out);
            end
        end
    elseif strcmp(style, 'slider')
        out=get(handle, 'Value');
    elseif strcmp(style, 'popupmenu')
        out=get(handle, 'Value');
    else
        out=get(handle, 'Value');
    end