Description of setStatusString
Home > Imaging > guis > gui_handling > setStatusString.m
setStatusString
PURPOSE
This function sets the status field in mainControls.
SYNOPSIS
function setStatusString(st)
DESCRIPTION
 This function sets the status field in mainControls.
CROSS-REFERENCE INFORMATION
This function calls:
updateGUIByGlobal given the name of a global variable, find and update the GUI that contains it
This function is called by:
fluorAnalysisSettings FLUORANALYSISSETTINGS M-file for fluorAnalysisSettings.fig
loadFluorAnalysisSettings
ratios RATIOS M-file for ratios.fig
runFrameAnalysis
runLineScanAnalysis
saveFluorAnalysisSettings
saveFluorAnalysisSettingsAs
applyBlasterParking
blaster BLASTER M-file for blaster.fig
loadBlasterSetup
saveBlasterSetup
saveBlasterSetupAs save pulse set to disk with new name
fieldAdjustGUI FIELDADJUSTGUI M-file for fieldAdjustGUI.fig
makeImageFigures
motorGUI MOTORGUI Application M-file for motorGUI.fig
resetImageProperties
closeConfigurationGUI
executeFocusCallback
executeGrabOneCallback
executeGrabOneStackCallback executeGrabOneCallback(h).m******
genericKeyPressFunction
setAcquisitionParameters
endAcquisition
makeFrameByStripes
loadConfig
openAndLoadConfiguration Allows user to select a configuration from disk and loads it
saveCurrentConfigAs
saveHeaderStructureAs
savingInfoIsOK updated by tp 10/25/01
setSavePath
loadPositionList
savePositionListAs
initImaging
mp285FinishMove mp285SetPos controls the position of the mp285
mp285GetPos mp285GetPos retrieves the position information from the mp285 controller
mp285StartMove mp285SetPos controls the position of the mp285
executeGoHome
gotoPosition
gotoZero
moveStackFocus
setMotorPosition
startMoveStackFocus
startSetMotorPosition
updateMotorPosition
abortFocus
abortGrab
getPMTOffsets
loadStandardModeConfig
multiBlaster
pickAndMove
selectConfigurationFromMenu
setTrackerReference
trackImage
calibratePCell
loadPcellLookupTable
pcellcontrol PCELLCONTROL Application M-file for pcellControl.fig
pickPcellBoxCenters
reloadPcellTables
savePcellLookupTable
timerProcess_Imaging
findValidCyclePosition
initTimer
loadAnalysisSetup
loadCycle
loadUserSettings Allows user to select a settings file (*.ini) from disk and loads it
saveAnalysisSetup
saveAnalysisSetupAs
saveCycle writes pulseSet to disk
saveCycleAs save pulse set to disk with new name
saveUserSettings
timerCallPackageFunctions
timerCheckIfAllAborted
timerDoOne
timerLoop
timerMainLoop
timerRegisterPackageDone
timerTrigger
traceAnalyzer TRACEANALYZER M-file for traceAnalyzer.fig
SOURCE CODE
function setStatusString(st)
% This function sets the status field in mainControls.
    global state gh
    state.internal.statusString=st;
    updateGUIByGlobal('state.internal.statusString');