Description of getUserDataField
Home > Imaging > guis > gui_handling > getUserDataField.m
getUserDataField
PURPOSE
returns value of field in 'UserData' or [] if that field does not exist
SYNOPSIS
function retVal=getUserDataField(handle, field)
DESCRIPTION
 returns value of field in 'UserData' or [] if that field does not exist
CROSS-REFERENCE INFORMATION
This function calls:
hasUserDataField checks if a field exists within the 'UserData' of a particular handle
This function is called by:
checkValidNumber function to check if entry in GUI is valid
doGUICallback calls the Callback function of a GUI if one has been set by the user
getGUIValue returns the value in a GUI
setGUIValue set the value displayed in a GUI to the given value
updateGUIGlobal update the value of a Global value to match that contained in its GUI
updateGUILinks
updateGUIVars updates the value displayed in a GUI to match that of an associated variable
updateVariable automatically updates a global variable when a GUI value has been changed
pcellcontrol PCELLCONTROL Application M-file for pcellControl.fig
SOURCE CODE
function retVal=getUserDataField(handle, field)
% returns value of field in 'UserData' or [] if that field does not exist
    if (hasUserDataField(handle, field))
        retVal=getfield(get(handle, 'UserData'), field);
    else
        retVal=[];
    end