Description of hasUserDataField
Home > Imaging > guis > gui_handling > hasUserDataField.m
hasUserDataField
PURPOSE
checks if a field exists within the 'UserData' of a particular handle
SYNOPSIS
function r=hasUserDataField(h, f)
DESCRIPTION
 checks if a field exists within the 'UserData' of a particular handle
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
checkValidNumber function to check if entry in GUI is valid
doGUICallback calls the Callback function of a GUI if one has been set by the user
getGUIValue returns the value in a GUI
getUserDataField returns value of field in 'UserData' or [] if that field does not exist
hasGUIBeenUsed
setGUIValue set the value displayed in a GUI to the given value
updateAllGUIVars udpates all GUIs in handle
updateGUIGlobal update the value of a Global value to match that contained in its GUI
updateGUILinks
updateGUIVars updates the value displayed in a GUI to match that of an associated variable
updateVariable automatically updates a global variable when a GUI value has been changed
SOURCE CODE
function r=hasUserDataField(h, f)
% checks if a field exists within the 'UserData' of a particular handle
    if ishandle(h)
        ud=get(h, 'UserData');
        length(ud);
        if (length(ud)>0)
            r=isfield(ud, f);
        else
            r=0;
        end
    else
        r=0;
    end