Description of structNameParts
Home > Imaging > guis > gui_handling > structNameParts.m
structNameParts
PURPOSE
SYNOPSIS
function [outTopName, outStructName, outFieldName] = structNameParts(s)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
addGUIOfGlobal add a GUI to the list of GUIs associated with a global variable
addOrRemoveConfigGlobal
existGlobal
getGlobalConfigStatus
getGuiOfGlobal
hideGUI
seeGUI makes a gui visible. expects string with name of gui
setGlobalConfigStatus
setUserDataByGUIName
updateGUIByName given the name of a GUI, updates its contents to reflect the current state of a global variable
updateGUIGlobal update the value of a Global value to match that contained in its GUI
updateGUILinks
updateGuiByStruct
createConfigFileFast
initGUIs opens and interprets and initialization file
initGUIs_OLD opens and interprets and initialization file
SOURCE CODE
function [outTopName, outStructName, outFieldName] = structNameParts(s)
    s=deblank(s);
    periods=findstr(s, '.');
    if length(periods)>0
        outTopName=s(1:periods(1)-1);
        outStructName=s(1:periods(length(periods))-1);
        outFieldName=s(periods(length(periods))+1:length(s));
    else
        outTopName=s;
        outStructName=[];
        outFieldName=[];
    end