Description of updateGUIGlobal
Home > Imaging > guis > gui_handling > updateGUIGlobal.m
updateGUIGlobal
PURPOSE
update the value of a Global value to match that contained in its GUI
SYNOPSIS
function updateGUIGlobal(handle)
DESCRIPTION
 update the value of a Global value to match that contained in its GUI
CROSS-REFERENCE INFORMATION
This function calls:
getGUIValue returns the value in a GUI
getUserDataField returns value of field in 'UserData' or [] if that field does not exist
hasUserDataField checks if a field exists within the 'UserData' of a particular handle
structNameParts
updateGUIByGlobal given the name of a global variable, find and update the GUI that contains it
This function is called by:
genericCallback
SOURCE CODE
function updateGUIGlobal(handle)
% update the value of a Global value to match that contained in its GUI
    if hasUserDataField(handle, 'Global')
        gName=getUserDataField(handle, 'Global');
        [topName, structName, fieldName]=structNameParts(gName);
        val=getGUIValue(handle);
        if isnumeric(val)
            val=num2str(val);
        else
            val=['''' val ''''];
        end
        eval(['global ' topName]);
        if exist(topName, 'var')
            if length(structName)>0
                eval([structName '=setfield(' structName ',''' fieldName ''',' val ');']);
            else
                eval([topName '=' val ';']);
            end
            updateGUIByGlobal(gName);
        else
            Disp(['Error: global ' topName ' not found']);
        end
    end