Description of updateGUIByGlobal
Home > Imaging > guis > gui_handling > updateGUIByGlobal.m
updateGUIByGlobal
PURPOSE
given the name of a global variable, find and update the GUI that contains it
SYNOPSIS
function updateGUIByGlobal(globalName)
DESCRIPTION
 given the name of a global variable, find and update the GUI that contains it
CROSS-REFERENCE INFORMATION
This function calls:
getGuiOfGlobal
updateGUIByName given the name of a GUI, updates its contents to reflect the current state of a global variable
updateHeaderString
This function is called by:
ratios RATIOS M-file for ratios.fig
applyBlasterParking
blaster BLASTER M-file for blaster.fig
loadBlasterSetup
selectBlasterConfigFromMenu
updateBlasterConfigDisplay
updateBlasterConfigLineDisplay
channelGUI
fieldAdjustGUI FIELDADJUSTGUI M-file for fieldAdjustGUI.fig
motorGUI MOTORGUI Application M-file for motorGUI.fig
siGUI_ImagingControls siGUI_ImagingControls Application M-file for siGUI_ImagingControls.fig
calculateStackParameters
figureButtonOverCallback
setAcquisitionParameters
setStatusString This function sets the status field in mainControls.
updateGUIGlobal update the value of a Global value to match that contained in its GUI
updateGuiByStruct
piezoUpdatePositionNoWait
endAcquisition
makeFrameByStripes
makeStripe makeStripe.m*****
resetCounters
opencfg opens and processes a CONFIG (*.CFG) FILE
saveCurrentConfigAs
checkFileBeforeSave This function checks if the file about to be saved already exists
savingInfoIsOK updated by tp 10/25/01
initGUIs opens and interprets and initialization file
initGUIs_OLD opens and interprets and initialization file
loadPositionList
initImaging
makeNewRotatedMirrorOutput
definePosition
distance
moveStackFocus
setMotorOffsets
startMoveStackFocus
updateRelativeMotorPosition
rotateMirrorData
SpineSelect
TNSetPath
abortFocus
flip_rot
putCurrentInCyclePos
restoreScan
restoreScanNoStack
setTrackerReference
settingsManager
stopAndRestartFocus
trackImage
updateCycleDisplay
setupImagingCyclePosition
siApplyDAQSampleRates
stackAndBlast
imSetScanningPower
pcellcontrol PCELLCONTROL Application M-file for pcellControl.fig
pickPcellBoxCenters
recallBoxSettings
makeTilerOutput
setTilerStatusString
tilerActionFunction
tilerControls TILERCONTROLS Application M-file for tilerControls.fig
timerProcess_Imaging
applyAdvancedCyclePosition
changeCyclePosition
cfChangeInputRate
findValidCyclePosition
initTimer
loadAnalysisSetup
loadCycle
saveCycleAs save pulse set to disk with new name
setTimerStatusString
timerMainLoop
timerRegisterPackageDone
timerResumeLoop
traceAnalyzer TRACEANALYZER M-file for traceAnalyzer.fig
updateLineDisplay
updatePeakDisplay
SOURCE CODE
function updateGUIByGlobal(globalName)
% given the name of a global variable, find and update the GUI that contains it
    guiLoc=getGuiOfGlobal(globalName);
    if isempty(guiLoc)
        % update header for those variables that do not have GUIs
        updateHeaderString(globalName);
    else
        updateGUIByName(guiLoc);    % update the GUI
    end