Description of hideGUI
Home > Imaging > guis > gui_handling > hideGUI.m
hideGUI
PURPOSE
SYNOPSIS
function hideGUI(GUI)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
structNameParts
This function is called by:
closeChannelGUI
closeConfigurationGUI
closeControlsGUI
closeImageGUI closeImageGUI.m****
closeStandardModeGUI
timerDoOne
timerLoop
SOURCE CODE
function hideGUI(GUI)
    [topName, s, f]=structNameParts(GUI);
    eval(['global ' topName]);
    eval(['set(' GUI ', ''Visible'', ''off'')']);