Description of setGUIValue
Home > Imaging > guis > gui_handling > setGUIValue.m
setGUIValue
PURPOSE
set the value displayed in a GUI to the given value
SYNOPSIS
function setGUIValue(handle, val)
DESCRIPTION
 set the value displayed in a GUI to the given value
CROSS-REFERENCE INFORMATION
This function calls:
getUserDataField returns value of field in 'UserData' or [] if that field does not exist
hasUserDataField checks if a field exists within the 'UserData' of a particular handle
This function is called by:
updateGUIVars updates the value displayed in a GUI to match that of an associated variable
timerMainControls TIMERMAINCONTROLS M-file for timerMainControls.fig
SOURCE CODE
function setGUIValue(handle, val)
% set the value displayed in a GUI to the given value
    switch get(handle, 'Style')
        case 'edit'
            if hasUserDataField(handle, 'Numeric')
                if getUserDataField(handle, 'Numeric') & ischar(val)
                    val=str2num(val);
                end
            end
            set(handle, 'String', val);
        case 'text'
            set(handle, 'String', val);
        case 'slider'
            if ischar(val)
                val=str2num(val)
            end
            set(handle, 'Value', val);
        case 'popupmenu'
            if ischar(val)
                val=str2num(val)
            end
            set(handle, 'Value', val);
        case 'checkbox'
            set(handle, 'Value', val);
        case 'radiobutton'
            set(handle, 'Value', val);
        otherwise
            disp(['setGUIValue: Style not implemented ' get(handle, 'Style')]);
    end