Description of updateKeepAllSlicesCheckMark
Home > Imaging > guis > gui_handling > updateKeepAllSlicesCheckMark.m
updateKeepAllSlicesCheckMark
PURPOSE
BSMOD - 1/1/2 - sets check mark next to keepAllSlicesInMemory selection in settings menu
SYNOPSIS
function updateKeepAllSlicesCheckMark
DESCRIPTION
 BSMOD - 1/1/2 - sets check mark next to keepAllSlicesInMemory selection in settings menu
CROSS-REFERENCE INFORMATION
This function calls:
getPullDownMenuIndex
This function is called by:
toggleKeepAllSlicesInMemory BSMOD - 1/1/2 - callback when user selects 'keepAllSlicesInMemory' from 'settings' menu
initImaging
timerUserSettings_Imaging
SOURCE CODE
function updateKeepAllSlicesCheckMark
% BSMOD - 1/1/2 - sets check mark next to keepAllSlicesInMemory selection in settings menu
    global gh state
    % get the index of the standard mode selection of the settings menu
    children=get(gh.siGUI_ImagingControls.Settings, 'Children');
    index=getPullDownMenuIndex(gh.siGUI_ImagingControls.Settings, 'Keep all slices in memory');
    if state.internal.keepAllSlicesInMemory==0
        set(children(index), 'Checked', 'off');
        if ~state.files.autoSave
            beep;
            errordlg({ ...
                '''Keep All Slices In Memory'' is OFF and ''Auto Save'' is OFF.' , ...
                'Data will be lost for all acquisitions of more than 1 slice.', ...
                'Recommend turning ''Auto Save'' on.'}, ...
                'Warning', 0);
        end
    else
        set(children(index), 'Checked', 'on');
    end