Description of updateGUIVars
Home > Imaging > guis > gui_handling > updateGUIVars.m
updateGUIVars
PURPOSE
updates the value displayed in a GUI to match that of an associated variable
SYNOPSIS
function updateGUIVars(handle)
DESCRIPTION
 updates the value displayed in a GUI to match that of an associated variable
CROSS-REFERENCE INFORMATION
This function calls:
getGlobalValue
getUserDataField returns value of field in 'UserData' or [] if that field does not exist
hasUserDataField checks if a field exists within the 'UserData' of a particular handle
setGUIValue set the value displayed in a GUI to the given value
updateHeaderString
This function is called by:
updateAllGUIVars udpates all GUIs in handle
SOURCE CODE
function updateGUIVars(handle)
% updates the value displayed in a GUI to match that of an associated variable
    if ~hasUserDataField(handle, 'Global')
        return
    end
    glo=getUserDataField(handle, 'Global');
    setGUIValue(handle, getGlobalValue(glo));
    updateHeaderString(glo);