Description of updateHeaderString
Home > Imaging > io > file_io > data > updateHeaderString.m
updateHeaderString
PURPOSE
SYNOPSIS
function updateHeaderString(globalName)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
getGlobalConfigStatus
This function is called by:
blaster BLASTER M-file for blaster.fig
fieldAdjustGUI FIELDADJUSTGUI M-file for fieldAdjustGUI.fig
updateGUIByGlobal given the name of a global variable, find and update the GUI that contains it
updateGUIVars updates the value displayed in a GUI to match that of an associated variable
writeData
makeNewPcellRepeatedOutput
setMotorPosition
startSetMotorPosition
updateMotorPosition
applyImagingInputParams
getPMTOffsets
pcellcontrol PCELLCONTROL Application M-file for pcellControl.fig
initTimer
SOURCE CODE
function updateHeaderString(globalName)
    global state
    flag=getGlobalConfigStatus(globalName);
    if ~bitand(flag, 2)
        return
    end
    pos=findstr(state.headerString, [globalName '=']);
    val=eval(globalName);
    if ~isnumeric(val) & ~ischar(val)
        val
        disp(['updateHeaderString: unknown type for ' globalName]);
        val='0';
    elseif isnumeric(val)
%         if length(val)~=1
%             val=0;
%         end
%         val=num2str(val);
        if length(val) ~=1
            sval='';                                        %Fitz MOD
            for i=1:length(val)
                sval=[sval strtrim(num2str(val(i))) ','];
            end
            val=sval;
        else                                                %Fitz MOD
            val=num2str(val);
        end
    else
        val=['''' val ''''];
    end
    if length(pos)==0
        state.headerString=[state.headerString globalName '=' val 13];
    else
        cr=findstr(state.headerString, 13);
        index=find(cr>pos);
        next=cr(index(1));
        if length(next)==0
            state.headerString=[state.headerString(1:pos-1) globalName '=' val 13];
        else
            state.headerString=[state.headerString(1:pos-1) globalName '=' val state.headerString(next:end)];
        end
    end