Description of toggleKeepAllSlicesInMemory
Home > Imaging > guis > gui_callbacks > toggleKeepAllSlicesInMemory.m
toggleKeepAllSlicesInMemory
PURPOSE
BSMOD - 1/1/2 - callback when user selects 'keepAllSlicesInMemory' from 'settings' menu
SYNOPSIS
function toggleKeepAllSlicesInMemory
DESCRIPTION
 BSMOD - 1/1/2 - callback when user selects 'keepAllSlicesInMemory' from 'settings' menu
CROSS-REFERENCE INFORMATION
This function calls:
getPullDownMenuIndex
updateKeepAllSlicesCheckMark BSMOD - 1/1/2 - sets check mark next to keepAllSlicesInMemory selection in settings menu
preallocateMemory
This function is called by:
SOURCE CODE
function toggleKeepAllSlicesInMemory
% BSMOD - 1/1/2 - callback when user selects 'keepAllSlicesInMemory' from 'settings' menu
    global gh state
    % get the index of the standard mode selection of the settings menu
    children=get(gh.siGUI_ImagingControls.Settings, 'Children');
    index=getPullDownMenuIndex(gh.siGUI_ImagingControls.Settings, 'Keep all slices in memory');
    checkState=get(children(index), 'Checked'); % check state of check mark nexted to 'autosave' option
    if strcmp(checkState,'on')     % it is on, so turn it off
        state.internal.keepAllSlicesInMemory=0;
    else
        state.internal.keepAllSlicesInMemory=1;
    end
    preallocateMemory;
    updateKeepAllSlicesCheckMark;