Description of updateFullFileName
Home > Imaging > guis > gui_callbacks > updateFullFileName.m
updateFullFileName
PURPOSE
SYNOPSIS
function updateFullFileName(h)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
zeroPadNum2Str
This function is called by:
checkFileBeforeSave This function checks if the file about to be saved already exists
saveHeaderStructureAs
savingInfoIsOK updated by tp 10/25/01
setSavePath
TNSetPath
timerRegisterPackageDone
SOURCE CODE
function updateFullFileName(h)
    global state
    if ~ischar(state.files.baseName)
        state.files.baseName='';
    end
    if ~ischar(state.files.savePath)
        state.files.savePath='';
    end
    try
        state.files.fullFileName=fullfile(state.files.savePath, [state.files.baseName zeroPadNum2Str(state.files.fileCounter)]);
    catch
    end